services:
  app:
    build: . #Creer une image a partir du Dockerfile courant
    image: laravelapp
    entrypoint: /project/entrypoint.sh
    restart: unless-stopped
    ports:
      - "7000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env
      - ./app/.env
        #environment:
        #- POSTGRES_USER=${DB_USERNAME}
        #- POSTGRES_PASSWORD=${DB_PASSWORD}
        #- POSTGRES_DB=${DB_DATABASE}
volumes: 
  dbdata:
  
